using BM2.Domain.Entities;
using BM2.Domain.Entities.System;

namespace BM2.Infrastructure.Seeders;

internal static class CurrencySeeder
{
    internal static async Task SeedAsync(BM2DbContext context)
    {
        if (!context.Currencies.Any())
        {
            await context.Currencies.AddRangeAsync(GetCurrencies());

            await context.SaveChangesAsync();
        }
    }

    private static List<Currency> GetCurrencies()
    {
        return
        [
            Currency.CreateInstance("Albania Lek", "Lek", "ALL", "Albania"),
            Currency.CreateInstance("Afghanistan Afghani", "؋", "AFN", "Afghanistan"),
            Currency.CreateInstance("Argentina Peso", "$", "ARS", "Argentina"),
            Currency.CreateInstance("Aruba Guilder", "ƒ", "AWG", "Aruba"),
            Currency.CreateInstance("Australia Dollar", "$", "AUD", "Australia"),
            Currency.CreateInstance("Azerbaijan Manat", "₼", "AZN", "Azerbaijan"),
            Currency.CreateInstance("Bahamas Dollar", "$", "BSD", "Bahamas"),
            Currency.CreateInstance("Barbados Dollar", "$", "BBD", "Barbados"),
            Currency.CreateInstance("Belarus Ruble", "Br", "BYN", "Belarus"),
            Currency.CreateInstance("Belize Dollar", "BZ$", "BZD", "Belize"),
            Currency.CreateInstance("Bermuda Dollar", "$", "BMD", "Bermuda"),
            Currency.CreateInstance("Bolivia Bolíviano", "$b", "BOB", "Bolivia"),
            Currency.CreateInstance("Bosnia and Herzegovina Convertible Mark", "KM", "BAM", "Bosnia and Herzegovina"),
            Currency.CreateInstance("Botswana Pula", "P", "BWP", "Botswana"),
            Currency.CreateInstance("Bulgaria Lev", "лв", "BGN", "Bulgaria"),
            Currency.CreateInstance("Brazil Real", "R$", "BRL", "Brazil"),
            Currency.CreateInstance("Brunei Darussalam Dollar", "$", "BND", "Brunei"),
            Currency.CreateInstance("Cambodia Riel", "៛", "KHR", "Cambodia"),
            Currency.CreateInstance("Canada Dollar", "$", "CAD", "Canada"),
            Currency.CreateInstance("Cayman Islands Dollar", "$", "KYD", "Cayman Islands"),
            Currency.CreateInstance("Chile Peso", "$", "CLP", "Chile"),
            Currency.CreateInstance("China Yuan Renminbi", "¥", "CNY", "China"),
            Currency.CreateInstance("Colombia Peso", "$", "COP", "Colombia"),
            Currency.CreateInstance("Costa Rica Colon", "₡", "CRC", "Costa Rica"),
            Currency.CreateInstance("Croatia Kuna", "kn", "HRK", "Croatia"),
            Currency.CreateInstance("Cuba Peso", "₱", "CUP", "Cuba"),
            Currency.CreateInstance("Czech Republic Koruna", "Kč", "CZK", "Czech Republic"),
            Currency.CreateInstance("Denmark Krone", "kr", "DKK", "Denmark"),
            Currency.CreateInstance("Dominican Republic Peso", "RD$", "DOP", "Dominican Republic"),
            Currency.CreateInstance("East Caribbean Dollar", "$", "XCD", "East Caribbean"),
            Currency.CreateInstance("Egypt Pound", "£", "EGP", "Egypt"),
            Currency.CreateInstance("El Salvador Colon", "$", "SVC", "El Salvador"),
            Currency.CreateInstance("Euro", "€", "EUR", "Eurozone"),
            Currency.CreateInstance("Falkland Islands (Malvinas) Pound", "£", "FKP", "Falkland Islands"),
            Currency.CreateInstance("Fiji Dollar", "$", "FJD", "Fiji"),
            Currency.CreateInstance("Ghana Cedi", "¢", "GHS", "Ghana"),
            Currency.CreateInstance("Gibraltar Pound", "£", "GIP", "Gibraltar"),
            Currency.CreateInstance("Guatemala Quetzal", "Q", "GTQ", "Guatemala"),
            Currency.CreateInstance("Guernsey Pound", "£", "GGP", "Guernsey"),
            Currency.CreateInstance("Guyana Dollar", "$", "GYD", "Guyana"),
            Currency.CreateInstance("Honduras Lempira", "L", "HNL", "Honduras"),
            Currency.CreateInstance("Hong Kong Dollar", "$", "HKD", "Hong Kong"),
            Currency.CreateInstance("Hungary Forint", "Ft", "HUF", "Hungary"),
            Currency.CreateInstance("Iceland Krona", "kr", "ISK", "Iceland"),
            Currency.CreateInstance("India Rupee", "", "INR", "India"),
            Currency.CreateInstance("Indonesia Rupiah", "Rp", "IDR", "Indonesia"),
            Currency.CreateInstance("Iran Rial", "﷼", "IRR", "Iran"),
            Currency.CreateInstance("Isle of Man Pound", "£", "IMP", "Isle of Man"),
            Currency.CreateInstance("Israel Shekel", "₪", "ILS", "Israel"),
            Currency.CreateInstance("Jamaica Dollar", "J$", "JMD", "Jamaica"),
            Currency.CreateInstance("Japan Yen", "¥", "JPY", "Japan"),
            Currency.CreateInstance("Jersey Pound", "£", "JEP", "Jersey"),
            Currency.CreateInstance("Kazakhstan Tenge", "лв", "KZT", "Kazakhstan"),
            Currency.CreateInstance("Korea (North) Won", "₩", "KPW", "North Korea"),
            Currency.CreateInstance("Korea (South) Won", "₩", "KRW", "South Korea"),
            Currency.CreateInstance("Kyrgyzstan Som", "лв", "KGS", "Kyrgyzstan"),
            Currency.CreateInstance("Laos Kip", "₭", "LAK", "Laos"),
            Currency.CreateInstance("Lebanon Pound", "£", "LBP", "Lebanon"),
            Currency.CreateInstance("Liberia Dollar", "$", "LRD", "Liberia"),
            Currency.CreateInstance("Macedonia Denar", "ден", "MKD", "North Macedonia"),
            Currency.CreateInstance("Malaysia Ringgit", "RM", "MYR", "Malaysia"),
            Currency.CreateInstance("Mauritius Rupee", "₨", "MUR", "Mauritius"),
            Currency.CreateInstance("Mexico Peso", "$", "MXN", "Mexico"),
            Currency.CreateInstance("Mongolia Tughrik", "₮", "MNT", "Mongolia"),
            Currency.CreateInstance("Mozambique Metical", "MT", "MZN", "Mozambique"),
            Currency.CreateInstance("Namibia Dollar", "$", "NAD", "Namibia"),
            Currency.CreateInstance("Nepal Rupee", "₨", "NPR", "Nepal"),
            Currency.CreateInstance("Netherlands Antilles Guilder", "ƒ", "ANG", "Netherlands Antilles"),
            Currency.CreateInstance("New Zealand Dollar", "$", "NZD", "New Zealand"),
            Currency.CreateInstance("Nicaragua Cordoba", "C$", "NIO", "Nicaragua"),
            Currency.CreateInstance("Nigeria Naira", "₦", "NGN", "Nigeria"),
            Currency.CreateInstance("Norway Krone", "kr", "NOK", "Norway"),
            Currency.CreateInstance("Oman Rial", "﷼", "OMR", "Oman"),
            Currency.CreateInstance("Pakistan Rupee", "₨", "PKR", "Pakistan"),
            Currency.CreateInstance("Panama Balboa", "B/.", "PAB", "Panama"),
            Currency.CreateInstance("Paraguay Guarani", "Gs", "PYG", "Paraguay"),
            Currency.CreateInstance("Peru Sol", "S/.", "PEN", "Peru"),
            Currency.CreateInstance("Philippines Peso", "₱", "PHP", "Philippines"),
            Currency.CreateInstance("Poland Zloty", "zł", "PLN", "Poland"),
            Currency.CreateInstance("Qatar Riyal", "﷼", "QAR", "Qatar"),
            Currency.CreateInstance("Romania Leu", "lei", "RON", "Romania"),
            Currency.CreateInstance("Russia Ruble", "₽", "RUB", "Russia"),
            Currency.CreateInstance("Saint Helena Pound", "£", "SHP", "Saint Helena"),
            Currency.CreateInstance("Saudi Arabia Riyal", "﷼", "SAR", "Saudi Arabia"),
            Currency.CreateInstance("Serbia Dinar", "Дин.", "RSD", "Serbia"),
            Currency.CreateInstance("Seychelles Rupee", "₨", "SCR", "Seychelles"),
            Currency.CreateInstance("Singapore Dollar", "$", "SGD", "Singapore"),
            Currency.CreateInstance("Solomon Islands Dollar", "$", "SBD", "Solomon Islands"),
            Currency.CreateInstance("Somalia Shilling", "S", "SOS", "Somalia"),
            Currency.CreateInstance("South Africa Rand", "R", "ZAR", "South Africa"),
            Currency.CreateInstance("Sri Lanka Rupee", "₨", "LKR", "Sri Lanka"),
            Currency.CreateInstance("Sweden Krona", "kr", "SEK", "Sweden"),
            Currency.CreateInstance("Switzerland Franc", "CHF", "CHF", "Switzerland"),
            Currency.CreateInstance("Suriname Dollar", "$", "SRD", "Suriname"),
            Currency.CreateInstance("Syria Pound", "£", "SYP", "Syria"),
            Currency.CreateInstance("Taiwan New Dollar", "NT$", "TWD", "Taiwan"),
            Currency.CreateInstance("Thailand Baht", "฿", "THB", "Thailand"),
            Currency.CreateInstance("Trinidad and Tobago Dollar", "TT$", "TTD", "Trinidad and Tobago"),
            Currency.CreateInstance("Turkey Lira", "", "TRY", "Turkey"),
            Currency.CreateInstance("Tuvalu Dollar", "$", "TVD", "Tuvalu"),
            Currency.CreateInstance("Ukraine Hryvnia", "₴", "UAH", "Ukraine"),
            Currency.CreateInstance("United Kingdom Pound", "£", "GBP", "United Kingdom"),
            Currency.CreateInstance("United States Dollar", "$", "USD", "United States"),
            Currency.CreateInstance("Uruguay Peso", "$U", "UYU", "Uruguay"),
            Currency.CreateInstance("Uzbekistan Som", "лв", "UZS", "Uzbekistan"),
            Currency.CreateInstance("Venezuela Bolívar", "Bs", "VEF", "Venezuela"),
            Currency.CreateInstance("Viet Nam Dong", "₫", "VND", "Vietnam"),
            Currency.CreateInstance("Yemen Rial", "﷼", "YER", "Yemen"),
            Currency.CreateInstance("Zimbabwe Dollar", "Z$", "ZWD", "Zimbabwe")
        ];
    }
}